// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVSEp_n3pUmWnVxPLlNYXkNFOt2YjBqPI',
    appId: '1:74824079029:web:db2646fd7dfcec018a10fc',
    messagingSenderId: '74824079029',
    projectId: 'sportslink-8f8a5',
    authDomain: 'sportslink-8f8a5.firebaseapp.com',
    storageBucket: 'sportslink-8f8a5.firebasestorage.app',
    measurementId: 'G-C9CV21KEGX',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9G6ND0od3Iv736QevQjmzfBPjYx9O058',
    appId: '1:74824079029:ios:ee30a882e84300b68a10fc',
    messagingSenderId: '74824079029',
    projectId: 'sportslink-8f8a5',
    storageBucket: 'sportslink-8f8a5.firebasestorage.app',
    androidClientId: '74824079029-c34ekbaf9hd6f7ntcel0spilu490c6hd.apps.googleusercontent.com',
    iosClientId: '74824079029-t0d4o1v9tthv6nv9krqakd93kccpbbg0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9G6ND0od3Iv736QevQjmzfBPjYx9O058',
    appId: '1:74824079029:ios:ee30a882e84300b68a10fc',
    messagingSenderId: '74824079029',
    projectId: 'sportslink-8f8a5',
    storageBucket: 'sportslink-8f8a5.firebasestorage.app',
    androidClientId: '74824079029-c34ekbaf9hd6f7ntcel0spilu490c6hd.apps.googleusercontent.com',
    iosClientId: '74824079029-t0d4o1v9tthv6nv9krqakd93kccpbbg0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVSEp_n3pUmWnVxPLlNYXkNFOt2YjBqPI',
    appId: '1:74824079029:web:2258498973aaf9d78a10fc',
    messagingSenderId: '74824079029',
    projectId: 'sportslink-8f8a5',
    authDomain: 'sportslink-8f8a5.firebaseapp.com',
    storageBucket: 'sportslink-8f8a5.firebasestorage.app',
    measurementId: 'G-9MR4MQ66Q7',
  );
}
